mybatis:
  # mapper配置文件
  config-location: classpath:/mybatis/mybatis-config.xml
  # mmapper扫描
  mapper-locations: classpath:/mybatis/mapper/*.xml
  # 别名包
  type-aliases-package: top.ccxh.mapper.pojo
#通用mapper
mapper:
    mappers: top.ccxh.mapper.my.SysMapper
    not-empty: false
    identity: MYSQL

#分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql