server:
  port: 8099
  context-path: /
spring:
  profiles:
    active: datasource,mybatis,mvc
logging:
  level:
    top.ccxh.mapper.port: debug
config:
  file:
    local:
      img-path: 'D:\weidian_git\product-lib\product-web\src\main\resources\public\static\productImg'
      sql-path: 'D:\project\product-lib\product-web\src\main\resources\init.sql'
    show:
      url: '\static\productImg'