server:
  port: 8099
  context-path: /
spring:
  profiles:
    active: datasource,mybatis,mvc
logging:
  level:
    top.ccxh.mapper.port: debug
config:
  file:
    local:
     path: 'd:\Users\admin\Desktop\1\resources\public\static\productImg'
    show:
      url: '\static\productImg'
