spring:
  mvc:
    view:
      suffix: .ftl
      #prefix: /WEB-INF/
  resources:
    static-locations: file:D:\weidian_git\product-lib\product-web\src\main\resources\public
  freemarker:
    charset: UTF-8
    content-type: text/html; charset=utf-8
    template-loader-path: file:D:\weidian_git\product-lib\product-web\src\main\resources\ftl
    cache: false
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
